### PR TITLE
Make dependency on Hermann optional

### PR DESCRIPTION
**Pull request by smathieu**
We don't currently use Hermann. The latest version of lookout-zipkin would crash on book because of a LoadError.

### CODE REVIEW

**Comment by smathieu** [comment]
@jamescway @rtyler could one of you review this?

**Comment by jamescway** [comment]
@smathieu so this would cause L4E to not be able to work, but it would have the code still in there.  Is that the intention?

**Comment by smathieu** [comment]
@jamescway Yes. I think our configuration is currently using Scribe rather than Kafka.

Looking at the code a bit more closely, it seems like there's a possibility for the RackHandler to attempt to construct a `ZipkinKafkaTracer` when it could not exist. I'll address that and update the PR.

**Comment by jamescway** [comment]
@smathieu Which configuration are you looking at?  The stuff deployed to bare metal or the aws stuff?  The aws stuff is with kafka (thats what we're using now)  other stuff is deprecated.

**Pull request merged**
